# Язык плагина
locale: "ru"

# Настройки ActionBar
actionbar:
  timer-format:
    period: "&#FFAA55&lПериод {period}"
    paused: "&#FF5555&l[ПАУЗА]"

  penalty-format:
    admin: "&#FF5555{player} &f{reason} &d{time}"
    player: "&f{reason} &d{time}"

  separator: " &8| "
  max-penalties: 4
  show-timer: true
  show-pause: true

# Настройки автоматического матча
auto-match:
  period-duration: 15
  break-duration: 120

arena1:
  boatpoints: {}
  penalty-history: []

arena2:
  boatpoints: {}
  penalty-history: []

arena3:
  boatpoints: {}
  penalty-history: []

arena4:
  boatpoints: {}
  penalty-history: []

arena5:
  boatpoints: {}
  penalty-history: []

arena6:
  boatpoints: {}
  penalty-history: []

arena7:
  boatpoints: {}
  penalty-history: []

arena8:
  boatpoints: {}
  penalty-history: []

arena9:
  boatpoints: {}
  penalty-history: []

arena10:
  boatpoints: {}
  penalty-history: []

arena11:
  boatpoints: {}
  penalty-history: []

arena12:
  boatpoints: {}
  penalty-history: []

arena13:
  boatpoints: {}
  penalty-history: []

arena14:
  boatpoints: {}
  penalty-history: []

arena15:
  boatpoints: {}
  penalty-history: []

arena16:
  boatpoints: {}
  penalty-history: []

arena17:
  boatpoints: {}
  penalty-history: []

arena18:
  boatpoints: {}
  penalty-history: []

arena19:
  boatpoints: {}
  penalty-history: []

arena20:
  boatpoints: {}
  penalty-history: []

arena21:
  boatpoints: {}
  penalty-history: []

arena22:
  boatpoints: {}
  penalty-history: []

arena23:
  boatpoints: {}
  penalty-history: []

arena24:
  boatpoints: {}
  penalty-history: []

arena25:
  boatpoints: {}
  penalty-history: []

arena26:
  boatpoints: {}
  penalty-history: []

arena27:
  boatpoints: {}
  penalty-history: []

arena28:
  boatpoints: {}
  penalty-history: []

arena29:
  boatpoints: {}
  penalty-history: []

arena30:
  boatpoints: {}
  penalty-history: []

arena31:
  boatpoints: {}
  penalty-history: []

arena32:
  boatpoints: {}
  penalty-history: []

arena33:
  boatpoints: {}
  penalty-history: []

arena34:
  boatpoints: {}
  penalty-history: []

arena35:
  boatpoints: {}
  penalty-history: []

arena36:
  boatpoints: {}
  penalty-history: []

arena37:
  boatpoints: {}
  penalty-history: []

arena38:
  boatpoints: {}
  penalty-history: []

arena39:
  boatpoints: {}
  penalty-history: []

arena40:
  boatpoints: {}
  penalty-history: []

arena41:
  boatpoints: {}
  penalty-history: []

arena42:
  boatpoints: {}
  penalty-history: []

arena43:
  boatpoints: {}
  penalty-history: []

arena44:
  boatpoints: {}
  penalty-history: []

arena45:
  boatpoints: {}
  penalty-history: []

arena46:
  boatpoints: {}
  penalty-history: []

arena47:
  boatpoints: {}
  penalty-history: []

arena48:
  boatpoints: {}
  penalty-history: []

arena49:
  boatpoints: {}
  penalty-history: []

arena50:
  boatpoints: {}
  penalty-history: []